---
modules:
  - camera:
      path: "./socket"
  - line:
      sensor_count: 46
      pickup_threshold: 24
      trigger_threshold: 400
      uart_path: /dev/ttyUSB0
      baud_rate: 500000
  - server:
      addr: "0.0.0.0:7272"
