[package]
name = "camex"
version = "0.1.0"
edition = "2021"
# links = "nffi"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html 

[dependencies]
opencv = "0.65.0"
anyhow = "1.0.57"
ndarray = "0.15.4"
chrono = "0.4.19"