---
camera:
  enable_reading: false
  path: "./socket"
  orbit:
    curve_steepness: 2.718281828459045
    shift_x: 0.3
    shift_y: 1.0
  dampen:
    curve_steepness: 305.0
    shift_x: -1.0
    shift_y: 0.0
# line:
#   sensor_count: 46
#   pickup_threshold: 24
#   pickup_sensor_count: 30
#   trigger_threshold: 400
#   uart_path: /dev/ttyACM0
#   baud_rate: 500000
server:
  addr: "0.0.0.0:7272"
motors: ~
state_randomizer: false
