---
modules:
  # - camera:
      # path: "./socket"
  - line:
      sensor_count: 46
      pickup_threshold: 200
      uart_path: /dev/ttyACM0
      baud_rate: 500000
state_history:
  enable: false
  path: "./state.json"
