---
modules:
  # - camera:
  # path: "./socket"
  - line:
      sensor_count: 46
      trigger_threshold: 128
      pickup_threshold: 24
      uart_path: /dev/ttyACM1
      baud_rate: 500000
  - server:
      addr: "0.0.0.0:7272"
