// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BaseButton: typeof import('./src/components/BaseButton.vue')['default']
    BaseRadioButton: typeof import('./src/components/BaseRadioButton.vue')['default']
    BaseRangeSlider: typeof import('./src/components/BaseRangeSlider.vue')['default']
    BaseSlider: typeof import('./src/components/BaseSlider.vue')['default']
    BaseTabs: typeof import('./src/components/BaseTabs.vue')['default']
    BaseTextField: typeof import('./src/components/BaseTextField.vue')['default']
    ConfigEditor: typeof import('./src/components/ConfigEditor.vue')['default']
    'IMdi:deleteEmptyOutline': typeof import('~icons/mdi/delete-empty-outline')['default']
    IMdiArrowLeft: typeof import('~icons/mdi/arrow-left')['default']
    IMdiArrowRight: typeof import('~icons/mdi/arrow-right')['default']
    JSONEditor: typeof import('./src/components/JSONEditor.vue')['default']
  }
}

export { }
